import { StyleSheet } from "react-native";
import { ui } from "../theme/ui";

export const commonStyles = StyleSheet.create({
  // Auth / form (Settings-style: dark, glass boxes, rounded-xl)
  container: {
    padding: 20,
    flex: 1,
    justifyContent: "center",
  },
  authScreen: {
    flex: 1,
    backgroundColor: ui.colors.background,
    paddingHorizontal: 24,
    paddingVertical: 24,
    justifyContent: "center",
  },
  authForm: {
    maxWidth: 400,
    alignSelf: "center",
    width: "100%",
    gap: 24,
  },
  authTitle: {
    fontSize: 22,
    fontWeight: "600",
    color: ui.colors.text,
    textAlign: "center",
  },
  authField: {
    gap: 8,
  },
  authLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: ui.colors.muted,
  },
  authInput: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: ui.colors.glass,
    borderWidth: 1,
    borderColor: ui.colors.glassBorder,
    color: ui.colors.text,
    fontSize: 16,
  },
  authPrimaryButton: {
    width: "100%",
    paddingVertical: 16,
    borderRadius: 12,
    backgroundColor: ui.colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  authPrimaryButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  authSecondaryButton: {
    width: "100%",
    paddingVertical: 16,
    borderRadius: 12,
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: ui.colors.glassBorder,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,
  },
  authSecondaryButtonText: {
    color: ui.colors.muted,
    fontSize: 14,
    fontWeight: "600",
  },
  authError: {
    color: "#FCA5A5",
    fontSize: 14,
    marginBottom: 8,
  },
  title: {
    fontSize: 28,
    marginBottom: 20,
    fontWeight: "bold",
  },
  input: {
    borderWidth: 1,
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
  },
  button: {
    backgroundColor: "#007AFF",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 8,
    marginTop: 12,
  },
  buttonText: {
    color: "white",
    textAlign: "center",
    fontWeight: "bold",
  },
  error: {
    color: "red",
    marginBottom: 8,
  },

  // Library
  libraryScreen: {
    flex: 1,
    backgroundColor: "#9EC8FF",
  },
  homeContent: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  libraryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  libraryHeaderTitle: {
    fontSize: 18,
    fontWeight: "bold",
  },
  libraryProfileCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#007AFF",
    justifyContent: "center",
    alignItems: "center",
  },
  libraryProfileInitial: {
    color: "#fff",
    fontWeight: "bold",
  },
  libraryListContent: {
    padding: 16,
  },
  libraryCard: {
    flexDirection: "row",
    backgroundColor: "#D9EFFF",
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  libraryCarImage: {
    width: 110,
    height: 110,
    borderRadius: 8,
    marginRight: 12,
  },

  // Home screen
  homeRoot: {
    flex: 1,
    backgroundColor: ui.colors.background,
    alignItems: "center",
    overflow: "hidden",
  },
  homeContentWrapper: {
    flex: 1,
    position: "relative",
    zIndex: 10,
    width: "100%",
    paddingHorizontal: 24,
    alignItems: "center",
  },
  homeRocketContainer: {
    position: "absolute",
    left: "50%",
    top: "50%",
    width: 118,
    height: 118,
    marginLeft: -59,
    marginTop: -59,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 20,
  },
  buttonsWrap: {
    position: "absolute",
    left: "50%",
    width: 360,
    marginLeft: -180,
    paddingHorizontal: 24,
    alignItems: "center",
    zIndex: 20,
    gap: 12,
  },
  titleBlock: {
    alignItems: "center",
    marginBottom: 4,
  },
  homeTitle: {
    fontSize: 40,
    fontWeight: "800",
    color: ui.colors.text,
    textShadowColor: "rgba(6,182,212,0.6)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 22,
    marginBottom: 6,
    letterSpacing: 0.4,
  },
  subtitle: {
    color: ui.colors.muted,
    fontSize: 13,
    letterSpacing: 0.5,
  },
  secondaryWrap: {
    width: "100%",
    maxWidth: 360,
    gap: 12,
  },
  guestWrap: {
    width: "100%",
    maxWidth: 360,
    alignItems: "center",
    marginTop: 8,
  },
  guestTitle: {
    color: ui.colors.text,
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 8,
  },
  guestText: {
    color: ui.colors.muted,
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
  },
  portalStage: {
    position: "absolute",
    top: "50%",
    left: "50%",
    width: 360,
    height: 360,
    marginLeft: -180,
    marginTop: -180,
    alignItems: "center",
    justifyContent: "center",
  },
  portalAura: {
    position: "absolute",
    width: 340,
    height: 340,
    borderRadius: 170,
    backgroundColor: "rgba(6,182,212,0.16)",
  },
  portalMistLeft: {
    position: "absolute",
    left: -88,
    width: 170,
    height: 10,
    borderRadius: 999,
    backgroundColor: "rgba(6,182,212,0.55)",
    shadowColor: ui.colors.secondary,
    shadowOpacity: 0.85,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 0 },
  },
  portalMistRight: {
    position: "absolute",
    right: -88,
    width: 170,
    height: 10,
    borderRadius: 999,
    backgroundColor: "rgba(124,58,237,0.52)",
    shadowColor: ui.colors.primary,
    shadowOpacity: 0.85,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 0 },
  },
  spark: {
    position: "absolute",
    borderRadius: 999,
    backgroundColor: ui.colors.secondary,
  },
  sparkLeft: {
    left: 12,
  },
  sparkRight: {
    right: 12,
    backgroundColor: ui.colors.primary,
  },
  portalRingWide: {
    position: "absolute",
    width: 226,
    height: 226,
    borderRadius: 113,
    borderWidth: 10,
    borderColor: "rgba(84,244,255,0.26)",
    shadowColor: "#54F4FF",
    shadowOpacity: 1,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 0 },
  },
  portalRingOuter: {
    position: "absolute",
    width: 204,
    height: 204,
    borderRadius: 102,
    borderWidth: 4,
    borderColor: "rgba(197,255,255,0.95)",
    shadowColor: "#7DF9FF",
    shadowOpacity: 1,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 0 },
  },
  portalRingInner: {
    position: "absolute",
    width: 188,
    height: 188,
    borderRadius: 94,
    borderWidth: 3,
    borderColor: "rgba(84,244,255,0.9)",
    shadowColor: "#54F4FF",
    shadowOpacity: 1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 0 },
  },
  portalCoreGlow: {
    position: "absolute",
    width: 164,
    height: 164,
    borderRadius: 82,
    backgroundColor: "rgba(0, 229, 255, 0.15)",
  },
  portalCore: {
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: "rgba(3, 12, 20, 0.92)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.04)",
  },
  actionBtn: {
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
  },
  glassBtn: {
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.13)",
  },
  secondaryBtn: {
    backgroundColor: "rgba(6,182,212,0.12)",
    borderWidth: 1,
    borderColor: "rgba(6,182,212,0.38)",
  },
  logoutBtn: {
    backgroundColor: "rgba(239,68,68,0.1)",
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.32)",
  },
  actionGlow: {
    position: "absolute",
    inset: 0,
  },
  primaryGlow: {
    backgroundColor: "rgba(124,58,237,0.16)",
  },
  secondaryGlow: {
    backgroundColor: "rgba(6,182,212,0.16)",
  },
  logoutGlow: {
    backgroundColor: "rgba(239,68,68,0.14)",
  },
  actionBtnText: {
    color: ui.colors.text,
    fontSize: 14,
    fontWeight: "600",
  },
  secondaryBtnText: {
    color: ui.colors.secondary,
  },
  logoutBtnText: {
    color: "#FCA5A5",
  },

  // ProfileButton
  profileWrap: {
    position: "absolute",
    top: 24,
    right: 24,
    zIndex: 50,
    borderRadius: 999,
  },
  profileButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(153,255,255,0.3)",
    overflow: "hidden",
  },
  profileGlow: {
    position: "absolute",
    top: -8,
    left: -8,
    right: -8,
    bottom: -8,
    borderRadius: 999,
    backgroundColor: "rgba(84,244,255,0.2)",
  },
  profileCore: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(6,16,24,0.65)",
  },

  // PromptSelection (SelectDestination-style)
  promptScreen: {
    flex: 1,
    backgroundColor: ui.colors.background,
    paddingBottom: 112,
  },
  promptHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingVertical: 16,
    backgroundColor: ui.colors.glass,
    borderBottomWidth: 1,
    borderBottomColor: ui.colors.glassBorder,
    gap: 16,
  },
  promptBackBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: ui.colors.glass,
    borderWidth: 1,
    borderColor: ui.colors.glassBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  promptHeaderText: {
    flex: 1,
  },
  promptHeaderTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: ui.colors.text,
  },
  promptHeaderSubtitle: {
    fontSize: 12,
    color: ui.colors.muted,
    marginTop: 2,
  },
  promptParticles: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 0,
  },
  promptCarouselWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    position: "relative",
    zIndex: 10,
    overflow: "visible",
  },
  promptCard: {
    width: 300,
    height: 360,
    borderRadius: 24,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.25)",
  },
  promptCardSelected: {
    borderWidth: 2,
    borderColor: ui.colors.primary,
    shadowColor: ui.colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 8,
  },
  promptCardImage: {
    width: "100%",
    height: "100%",
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  promptCardLabel: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
  },
  promptCardEmoji: {
    fontSize: 18,
    marginBottom: 4,
    color: ui.colors.text,
  },
  promptCardTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: ui.colors.text,
  },
  promptNavArrowRow: {
    position: "absolute",
    left: 0,
    right: 0,
    top: "50%",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    marginTop: -20,
    zIndex: 30,
  },
  promptNavArrow: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: ui.colors.glass,
    borderWidth: 1,
    borderColor: ui.colors.glassBorder,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 20,
  },
  promptNavLeft: {},
  promptNavRight: {},
  promptCylinder: {
    width: 360,
    height: 380,
    alignItems: "center",
    justifyContent: "center",
  },
  promptDestInfo: {
    marginTop: 32,
    alignItems: "center",
  },
  promptDestTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: ui.colors.text,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  promptDestSubtitle: {
    fontSize: 12,
    color: ui.colors.muted,
    marginTop: 8,
  },
  promptDestSubtitleSelected: {
    color: ui.colors.primary,
    fontWeight: "600",
  },
  promptDots: {
    flexDirection: "row",
    gap: 8,
    marginTop: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  promptDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "rgba(234,240,255,0.3)",
  },
  promptDotActive: {
    width: 24,
    height: 8,
    borderRadius: 4,
    backgroundColor: ui.colors.primary,
  },
  promptDotSelected: {
    backgroundColor: "rgba(124,58,237,0.6)",
  },
  promptConfirmBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
    backgroundColor: ui.colors.glass,
    borderTopWidth: 1,
    borderTopColor: ui.colors.glassBorder,
  },
  promptConfirmBtn: {
    width: "100%",
    paddingVertical: 16,
    borderRadius: 12,
    backgroundColor: ui.colors.primary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  promptConfirmBtnDisabled: {
    backgroundColor: ui.colors.glass,
  },
  promptConfirmBtnTextDisabled: {
    color: ui.colors.muted,
  },
  promptConfirmBtnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  promptSelectedCheck: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: ui.colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },

  // RocketButton
  rocketBtnContainer: {
    alignItems: "center",
  },
  rocketPressable: {
    alignItems: "center",
  },
  rocketMain: {
    width: 118,
    height: 118,
    alignItems: "center",
    justifyContent: "center",
  },
});
