import { StyleSheet } from "react-native";
import { ui } from "../theme/ui";
import { platformShadow, platformTextShadow } from "../utils/platformStyles";
import { centerContent, flexCenter, glassBorder, textBold, textMuted } from "./bases";

export const homeStyles = StyleSheet.create({
  uploadOverlay: { ...flexCenter, backgroundColor: "rgba(5,11,26,0.85)" },
  uploadCard: {
    ...centerContent,
    backgroundColor: ui.colors.glass,
    borderRadius: 24,
    padding: 40,
    borderWidth: 1,
    borderColor: "rgba(124,58,237,0.3)",
    minWidth: 260,
  },
  uploadText: { ...textBold, fontSize: 18, marginTop: 20 },
  uploadSubtext: { ...textMuted, marginTop: 8 },

  generationLimitIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "rgba(124, 58, 237, 0.2)",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginBottom: 16,
  },
  generationLimitTitle: {
    ...textBold,
    fontSize: 20,
    marginBottom: 12,
    color: ui.colors.text,
    textAlign: "center",
  },
  generationLimitBody: {
    ...textMuted,
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 14,
    textAlign: "center",
  },
  generationLimitSupportLink: {
    color: ui.colors.secondary,
    fontSize: 14,
    fontWeight: "700",
    textDecorationLine: "underline",
    marginBottom: 18,
  },
  generationLimitClose: {
    backgroundColor: ui.colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: "center",
    alignSelf: "stretch",
  },
  generationLimitCloseText: { ...textBold, fontSize: 15, color: "#fff" },

  homeRoot: {
    flex: 1,
    backgroundColor: ui.colors.background,
    alignItems: "center",
    overflow: "hidden",
  },
  homeContentWrapper: {
    flex: 1,
    position: "relative",
    zIndex: 10,
    width: "100%",
    paddingHorizontal: 24,
    alignItems: "center",
  },
  homeRocketContainer: {
    position: "absolute",
    left: "50%",
    top: "50%",
    width: 118,
    height: 118,
    marginLeft: -59,
    marginTop: -59,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 20,
  },
  buttonsWrap: {
    position: "absolute",
    left: "50%",
    width: 360,
    marginLeft: -180,
    paddingHorizontal: 24,
    alignItems: "center",
    zIndex: 20,
    gap: 12,
  },
  titleBlock: {
    alignItems: "center",
    marginBottom: 4,
  },
  homeTitle: {
    fontSize: 40,
    fontWeight: "800",
    color: ui.colors.text,
    marginBottom: 6,
    letterSpacing: 0.4,
    ...platformTextShadow({
      textShadowColor: "rgba(6,182,212,0.6)",
      textShadowOffset: { width: 0, height: 0 },
      textShadowRadius: 22,
    }),
  },
  slideShowSection: {
    alignSelf: "center",
    marginTop: 12,
  },
  slideShowSectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 0.2,
    textAlign: "center",
    color: ui.colors.text,
    marginBottom: 10,
  },
  slideShowContainer: {
    marginTop: 0,
    alignSelf: "center",
    overflow: "hidden",
    backgroundColor: "rgba(5,11,26,0.45)",
    borderWidth: 1,
    borderColor: "rgba(124,58,237,0.35)",
  },
  slidePage: {
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  slideImage: {
    width: "100%",
    height: "100%",
  },
  slideLocationOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 5,
    paddingHorizontal: 10,
    backgroundColor: "rgba(5, 8, 18, 0.5)",
  },
  slideLocationText: {
    color: "rgba(255,255,255,0.95)",
    fontSize: 11,
    fontWeight: "600",
    textAlign: "center",
    letterSpacing: 0.2,
    ...platformTextShadow({
      textShadowColor: "rgba(0,0,0,0.75)",
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 3,
    }),
  },
  slideShowLoading: {
    ...centerContent,
  },
  slideShowEmpty: {
    ...centerContent,
    padding: 10,
  },
  slideShowEmptyText: {
    ...textMuted,
    fontSize: 12,
    textAlign: "center",
  },
  secondaryWrap: {
    width: "100%",
    maxWidth: 360,
    gap: 12,
  },
  guestWrap: {
    width: "100%",
    maxWidth: 360,
    alignItems: "center",
    marginTop: 8,
  },
  guestTitle: {
    color: ui.colors.text,
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 8,
  },
  guestText: { ...textMuted, textAlign: "center", lineHeight: 20 },
  homeFooter: {
    position: "absolute",
    bottom: 14,
    alignSelf: "center",
    zIndex: 30,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  homeFooterLink: {
    color: ui.colors.secondary,
    fontSize: 14,
    fontWeight: "700",
    textDecorationLine: "underline",
  },
  portalStage: {
    ...centerContent,
    position: "absolute",
    top: "50%",
    left: "50%",
    width: 360,
    height: 360,
    marginLeft: -180,
    marginTop: -180,
  },
  portalAura: {
    position: "absolute",
    width: 340,
    height: 340,
    borderRadius: 170,
    backgroundColor: "rgba(6,182,212,0.16)",
  },
  portalMistLeft: {
    position: "absolute",
    left: -88,
    width: 170,
    height: 10,
    borderRadius: 999,
    backgroundColor: "rgba(6,182,212,0.55)",
    ...platformShadow({
      shadowColor: ui.colors.secondary,
      shadowOpacity: 0.85,
      shadowRadius: 20,
      shadowOffset: { width: 0, height: 0 },
    }),
  },
  portalMistRight: {
    position: "absolute",
    right: -88,
    width: 170,
    height: 10,
    borderRadius: 999,
    backgroundColor: "rgba(124,58,237,0.52)",
    ...platformShadow({
      shadowColor: ui.colors.primary,
      shadowOpacity: 0.85,
      shadowRadius: 20,
      shadowOffset: { width: 0, height: 0 },
    }),
  },
  spark: {
    position: "absolute",
    borderRadius: 999,
    backgroundColor: ui.colors.secondary,
  },
  sparkLeft: {
    left: 12,
  },
  sparkRight: {
    right: 12,
    backgroundColor: ui.colors.primary,
  },
  portalRingWide: {
    position: "absolute",
    width: 226,
    height: 226,
    borderRadius: 113,
    borderWidth: 10,
    borderColor: "rgba(84,244,255,0.26)",
    ...platformShadow({
      shadowColor: "#54F4FF",
      shadowOpacity: 1,
      shadowRadius: 28,
      shadowOffset: { width: 0, height: 0 },
    }),
  },
  portalRingOuter: {
    position: "absolute",
    width: 204,
    height: 204,
    borderRadius: 102,
    borderWidth: 4,
    borderColor: "rgba(197,255,255,0.95)",
    ...platformShadow({
      shadowColor: "#7DF9FF",
      shadowOpacity: 1,
      shadowRadius: 22,
      shadowOffset: { width: 0, height: 0 },
    }),
  },
  portalRingInner: {
    position: "absolute",
    width: 188,
    height: 188,
    borderRadius: 94,
    borderWidth: 3,
    borderColor: "rgba(84,244,255,0.9)",
    ...platformShadow({
      shadowColor: "#54F4FF",
      shadowOpacity: 1,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 0 },
    }),
  },
  portalCoreGlow: {
    position: "absolute",
    width: 164,
    height: 164,
    borderRadius: 82,
    backgroundColor: "rgba(0, 229, 255, 0.15)",
  },
  portalCore: {
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: "rgba(3, 12, 20, 0.92)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.04)",
  },
  actionBtn: {
    ...centerContent,
    overflow: "hidden",
    flexDirection: "row",
    gap: 12,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
  },
  glassBtn: { backgroundColor: "rgba(255,255,255,0.06)", ...glassBorder },
  secondaryBtn: {
    backgroundColor: "rgba(6,182,212,0.12)",
    borderWidth: 1,
    borderColor: "rgba(6,182,212,0.38)",
  },
  logoutBtn: {
    backgroundColor: "rgba(239,68,68,0.1)",
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.32)",
  },
  actionGlow: {
    position: "absolute",
    inset: 0,
  },
  primaryGlow: {
    backgroundColor: "rgba(124,58,237,0.16)",
  },
  secondaryGlow: {
    backgroundColor: "rgba(6,182,212,0.16)",
  },
  logoutGlow: {
    backgroundColor: "rgba(239,68,68,0.14)",
  },
  actionBtnText: { ...textBold, fontSize: 14 },
  secondaryBtnText: {
    color: ui.colors.secondary,
  },
  logoutBtnText: {
    color: "#FCA5A5",
  },
});
