import { StyleSheet } from "react-native";
import { ui } from "../theme/ui";
import { centerContent, textBold, textMuted } from "./bases";

export const libraryStyles = StyleSheet.create({
  libraryScreen: {
    flex: 1,
    backgroundColor: ui.colors.background,
  },
  libraryListContent: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 32,
  },
  libraryRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
    marginBottom: 10,
    gap: 10,
  },
  libraryTile: {
    borderRadius: 14,
    overflow: "hidden",
    padding: 3,
    backgroundColor: "rgba(5,11,26,0.75)",
    borderWidth: 2,
    borderColor: "rgba(124,58,237,0.55)",
    borderTopColor: "rgba(124,58,237,0.65)",
    borderLeftColor: "rgba(124,58,237,0.65)",
    borderRightColor: "rgba(6,182,212,0.35)",
    borderBottomColor: "rgba(6,182,212,0.35)",
  },
  libraryTileImage: {
    width: "100%",
    aspectRatio: 1,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  libraryEmptyWrap: {
    ...centerContent,
    paddingVertical: 48,
    paddingHorizontal: 24,
  },
  libraryEmptyTitle: {
    ...textBold,
    fontSize: 18,
    marginBottom: 8,
    textAlign: "center",
  },
  libraryEmptySubtitle: {
    ...textMuted,
    textAlign: "center",
    lineHeight: 20,
  },
  libraryLoadingWrap: {
    ...centerContent,
    paddingVertical: 48,
  },
  libraryLoadingText: {
    ...textMuted,
    marginTop: 12,
  },
  paginationWrap: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingBottom: 18,
    paddingTop: 6,
  },
  paginationBtn: {
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(124,58,237,0.4)",
    backgroundColor: "rgba(124,58,237,0.14)",
  },
  paginationBtnDisabled: {
    opacity: 0.45,
  },
  paginationBtnText: {
    ...textBold,
    fontSize: 13,
    color: ui.colors.text,
  },
  paginationMeta: {
    ...textMuted,
    fontSize: 13,
  },
  rotationAddBtn: {
    marginTop: 8,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 10,
    alignItems: "center",
    backgroundColor: "rgba(124, 58, 237, 0.2)",
    borderWidth: 1,
    borderColor: "rgba(124, 58, 237, 0.45)",
  },
  rotationAddBtnText: {
    ...textBold,
    fontSize: 13,
    color: ui.colors.text,
  },
  rotationSectionTitle: {
    ...textBold,
    fontSize: 16,
    paddingHorizontal: 16,
    marginTop: 4,
    marginBottom: 10,
  },
  rotationCurrentRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginHorizontal: 16,
    marginBottom: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: "rgba(8, 14, 32, 0.88)",
    borderWidth: 1,
    borderColor: "rgba(124, 58, 237, 0.28)",
  },
  rotationCurrentThumb: {
    width: 56,
    height: 56,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  rotationCurrentMeta: {
    flex: 1,
    minWidth: 0,
  },
  rotationCurrentLocation: {
    ...textBold,
    fontSize: 14,
  },
  rotationCurrentEmpty: {
    ...textMuted,
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  rotationRemoveBtn: {
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: "rgba(239, 68, 68, 0.14)",
    borderWidth: 1,
    borderColor: "rgba(248, 113, 113, 0.45)",
  },
  rotationRemoveBtnText: {
    ...textBold,
    fontSize: 13,
    color: "#f87171",
  },
});
