import { StyleSheet } from "react-native";
import { ui } from "../theme/ui";
import { platformShadow } from "../utils/platformStyles";
import { centerContent, glassBorder, iconButtonBase, textBold, textMuted } from "./bases";

export const PROMPT_WHEEL_ITEM_SIZE = 56;
export const PROMPT_WHEEL_ITEM_GAP = 12;

export const promptStyles = StyleSheet.create({
  promptScreen: {
    flex: 1,
    backgroundColor: ui.colors.background,
    paddingBottom: 112,
  },
  promptHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingVertical: 16,
    backgroundColor: ui.colors.headerBar,
    borderBottomWidth: 1,
    borderBottomColor: ui.colors.headerBarBorder,
    gap: 16,
  },
  promptBackBtn: {
    ...iconButtonBase,
    backgroundColor: ui.colors.glass,
    ...glassBorder,
  },
  promptHeaderText: {
    flex: 1,
  },
  promptHeaderTitle: { ...textBold, fontSize: 18 },
  promptHeaderSubtitle: { ...textMuted, fontSize: 12, marginTop: 2 },
  promptMgmtOptions: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 24,
    gap: 16,
  },
  promptMgmtBoardOuter: {
    flex: 1,
    borderRadius: 18,
    padding: 14,
    backgroundColor: ui.colors.boardDeep,
    borderWidth: 1,
    borderColor: ui.colors.boardDeepBorder,
    ...platformShadow({
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.35,
      shadowRadius: 16,
      elevation: 10,
    }),
    gap: 12,
  },
  promptMgmtOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 18,
    paddingHorizontal: 18,
    borderRadius: 14,
  },
  promptMgmtOptionCreate: {
    backgroundColor: ui.colors.boardViolet,
    borderColor: ui.colors.boardVioletBorder,
    borderLeftWidth: 4,
    borderLeftColor: ui.colors.primary,
  },
  promptMgmtOptionManageExisting: {
    backgroundColor: ui.colors.boardCyan,
    borderColor: ui.colors.boardCyanBorder,
    borderLeftWidth: 4,
    borderLeftColor: ui.colors.secondary,
  },
  promptMgmtOptionTitle: { ...textBold, fontSize: 16 },
  promptMgmtOptionSubtitle: { ...textMuted, fontSize: 13, marginTop: 4 },
  promptMgmtContentBoard: {
    flex: 1,
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 24,
    padding: 20,
    borderRadius: 18,
    backgroundColor: ui.colors.boardContent,
    borderWidth: 1,
    borderColor: ui.colors.boardContentBorder,
    borderTopWidth: 3,
    borderTopColor: ui.colors.secondary,
    ...platformShadow({
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 8,
    }),
  },
  promptMgmtContentBoardCreate: {
    borderTopColor: ui.colors.primary,
  },
  promptMgmtCreateScroll: {
    flex: 1,
  },
  promptMgmtCreateScrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 40,
  },
  promptMgmtFieldBox: {
    marginBottom: 14,
    padding: 14,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: ui.colors.boardVioletBorder,
    backgroundColor: "rgba(8, 14, 32, 0.65)",
  },
  promptMgmtHint: {
    ...textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  promptMgmtFieldBoxLabel: {
    ...textMuted,
    fontSize: 11,
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  promptMgmtCreatePreviewWrap: {
    width: "100%",
    aspectRatio: 16 / 9,
    borderRadius: 16,
    marginBottom: 10,
    backgroundColor: "rgba(0,0,0,0.45)",
    borderWidth: 2,
    borderColor: ui.colors.boardCyanBorder,
    overflow: "hidden",
  },
  promptMgmtCreateSectionLabel: {
    ...textBold,
    fontSize: 13,
    marginBottom: 8,
    marginTop: 4,
    color: ui.colors.secondary,
  },
  promptMgmtCreateConfirmBar: {
    marginTop: 16,
    padding: 14,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: ui.colors.primary,
    backgroundColor: "rgba(124, 58, 237, 0.12)",
    gap: 10,
  },
  promptMgmtCreateConfirmText: { ...textBold, fontSize: 15, textAlign: "center", marginBottom: 4 },
  promptMgmtCreateBtnRow: {
    flexDirection: "row",
    gap: 10,
  },
  promptMgmtCreateBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
  },
  promptMgmtCreateBtnYes: {
    backgroundColor: ui.colors.primary,
  },
  promptMgmtCreateBtnNo: {
    backgroundColor: ui.colors.glass,
    borderWidth: 1,
    borderColor: ui.colors.glassBorder,
  },
  promptMgmtListScroll: {
    flex: 1,
    paddingHorizontal: 14,
    paddingBottom: 24,
  },
  promptMgmtListRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginBottom: 12,
    borderRadius: 14,
    backgroundColor: ui.colors.boardDeep,
    borderWidth: 2,
    borderColor: ui.colors.boardCyanBorder,
    borderLeftWidth: 5,
    borderLeftColor: ui.colors.secondary,
    ...platformShadow({
      shadowColor: ui.colors.secondary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 6,
      elevation: 4,
    }),
  },
  promptMgmtListThumb: {
    width: 64,
    height: 64,
    borderRadius: 10,
    backgroundColor: ui.colors.glass,
    borderWidth: 2,
    borderColor: ui.colors.boardVioletBorder,
  },
  promptMgmtListTextCol: {
    flex: 1,
    minWidth: 0,
  },
  promptMgmtListTitle: { ...textBold, fontSize: 15 },
  promptMgmtListPrompt: { ...textMuted, fontSize: 13, marginTop: 4, lineHeight: 18 },
  promptMgmtListRowActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  promptMgmtListEditBtn: {
    padding: 8,
    borderRadius: 10,
    backgroundColor: "rgba(6, 182, 212, 0.12)",
    borderWidth: 1,
    borderColor: ui.colors.boardCyanBorder,
  },
  promptMgmtListDeleteBtn: {
    padding: 8,
    borderRadius: 10,
    backgroundColor: "rgba(239, 68, 68, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(248, 113, 113, 0.45)",
  },
  promptMgmtModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.72)",
    paddingHorizontal: 10,
    paddingTop: 12,
    paddingBottom: 10,
    justifyContent: "center",
  },
  promptMgmtModalScroll: {
    flex: 1,
    width: "100%",
  },
  promptMgmtModalScrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingVertical: 8,
  },
  promptMgmtModalCard: {
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 20,
    backgroundColor: ui.colors.boardContent,
    borderWidth: 2,
    borderColor: ui.colors.boardVioletBorder,
    maxHeight: "92%",
  },
  promptMgmtModalTitle: { ...textBold, fontSize: 19, marginBottom: 16 },
  promptMgmtModalMessage: { ...textMuted, fontSize: 14, lineHeight: 20, marginBottom: 8 },
  promptMgmtLabel: { ...textMuted, fontSize: 12, marginBottom: 6 },
  promptMgmtInput: {
    borderWidth: 1,
    borderColor: ui.colors.inputBorder,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: ui.colors.text,
    fontSize: 15,
    marginBottom: 12,
    backgroundColor: "rgba(0,0,0,0.25)",
  },
  promptMgmtInputMultiline: {
    minHeight: 140,
    textAlignVertical: "top",
  },
  promptMgmtModalPreviewWrap: {
    width: "100%",
    aspectRatio: 16 / 9,
    borderRadius: 16,
    marginBottom: 16,
    backgroundColor: "rgba(0,0,0,0.45)",
    borderWidth: 2,
    borderColor: ui.colors.boardCyanBorder,
    overflow: "hidden",
  },
  promptMgmtModalActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  promptMgmtModalBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
  },
  promptMgmtModalBtnSecondary: {
    backgroundColor: ui.colors.glass,
    borderWidth: 1,
    borderColor: ui.colors.glassBorder,
  },
  promptMgmtModalBtnPrimary: {
    backgroundColor: ui.colors.primary,
  },
  promptMgmtModalBtnDanger: {
    backgroundColor: "rgba(239,68,68,0.15)",
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.4)",
  },
  promptMgmtModalBtnText: { ...textBold, fontSize: 15 },
  promptMgmtModalBtnTextLight: { color: "#fff", fontWeight: "600" },
  promptMgmtChangeImageBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: ui.colors.boardViolet,
    borderWidth: 1,
    borderColor: ui.colors.boardVioletBorder,
    marginBottom: 12,
  },
  promptMgmtGeneratePreviewBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: ui.colors.primary,
    marginBottom: 12,
  },
  promptMgmtGeneratePreviewBtnDisabled: {
    opacity: 0.45,
  },
  promptMainColumn: {
    flex: 1,
    width: "100%",
    minHeight: 0,
  },
  promptCarouselWrap: {
    ...centerContent,
    flex: 1,
    paddingHorizontal: 16,
    position: "relative",
    zIndex: 10,
    overflow: "visible",
  },
  promptCylinderBlock: {
    position: "relative",
    width: "100%",
    alignItems: "center",
    minHeight: 380,
  },
  promptCard: {
    width: 300,
    height: 360,
    borderRadius: 24,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.25)",
  },
  promptCardSelected: {
    borderWidth: 2,
    borderColor: ui.colors.primary,
    ...platformShadow({
      shadowColor: ui.colors.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.5,
      shadowRadius: 12,
      elevation: 8,
    }),
  },
  promptCardImage: {
    width: "100%",
    height: "100%",
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  promptCardLabel: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
  },
  promptCardEmoji: {
    fontSize: 18,
    marginBottom: 4,
    color: ui.colors.text,
  },
  promptCardTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: ui.colors.text,
  },
  promptNavArrowRow: {
    position: "absolute",
    left: 0,
    right: 0,
    top: "50%",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    marginTop: -20,
    zIndex: 30,
  },
  promptNavArrow: {
    ...iconButtonBase,
    backgroundColor: ui.colors.glass,
    ...glassBorder,
    zIndex: 20,
  },
  promptNavLeft: {},
  promptNavRight: {},
  promptCylinder: { ...centerContent, width: 360, height: 380 },
  promptDestInfo: {
    marginTop: 32,
    alignItems: "center",
  },
  promptDestTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: ui.colors.text,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  promptDestSubtitle: { ...textMuted, fontSize: 12, marginTop: 8 },
  promptDestSubtitleSelected: {
    color: ui.colors.primary,
    fontWeight: "600",
  },
  promptDots: { ...centerContent, flexDirection: "row", gap: 8, marginTop: 16 },
  promptDestInfoWeb: {
    alignItems: "center",
    paddingHorizontal: 16,
    marginBottom: 10,
  },
  promptDotsWeb: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    width: "100%",
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  promptDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "rgba(234,240,255,0.3)",
  },
  promptDotActive: {
    width: 24,
    height: 8,
    borderRadius: 4,
    backgroundColor: ui.colors.primary,
  },
  promptDotSelected: {
    backgroundColor: "rgba(124,58,237,0.6)",
  },
  promptConfirmBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
    backgroundColor: ui.colors.glass,
    borderTopWidth: 1,
    borderTopColor: ui.colors.glassBorder,
  },
  promptConfirmBtn: {
    width: "100%",
    paddingVertical: 16,
    borderRadius: 12,
    backgroundColor: ui.colors.primary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  promptConfirmBtnDisabled: {
    backgroundColor: ui.colors.glass,
  },
  promptConfirmBtnTextDisabled: {
    color: ui.colors.muted,
  },
  promptConfirmBtnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  promptSelectedCheck: {
    ...centerContent,
    position: "absolute",
    top: 12,
    right: 12,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: ui.colors.primary,
  },

  promptPortalCarouselGlow: {
    position: "absolute",
    pointerEvents: "none",
    borderRadius: 999,
    opacity: 0.3,
    ...platformShadow({
      shadowColor: ui.colors.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.4,
      shadowRadius: 60,
      elevation: 20,
    }),
  },
  promptCylinderMutedText: textMuted,
  promptCylinderLoadingText: { ...textMuted, marginTop: 12 },
  promptScrollWheelWrap: {
    marginTop: 20,
    marginBottom: 8,
    alignSelf: "stretch",
    width: "100%",
  },
  promptScrollWheel: {
    width: "100%",
    height: PROMPT_WHEEL_ITEM_SIZE + 16,
    maxHeight: PROMPT_WHEEL_ITEM_SIZE + 16,
  },
  promptScrollWheelContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  promptScrollWheelItem: {
    ...centerContent,
    width: PROMPT_WHEEL_ITEM_SIZE + PROMPT_WHEEL_ITEM_GAP,
    height: PROMPT_WHEEL_ITEM_SIZE + 8,
  },
  promptScrollWheelItemActive: {
    transform: [{ scale: 1.08 }],
  },
  promptScrollWheelItemSelected: {
    borderWidth: 2,
    borderColor: ui.colors.primary,
    borderRadius: 14,
  },
  promptScrollWheelThumb: {
    width: PROMPT_WHEEL_ITEM_SIZE,
    height: PROMPT_WHEEL_ITEM_SIZE,
    borderRadius: 12,
    overflow: "hidden",
  },
  promptScrollWheelThumbPlaceholder: {
    ...centerContent,
    backgroundColor: ui.colors.glass,
  },
  promptScrollWheelEmoji: {
    fontSize: 24,
  },
  promptScrollWheelEmojiBadge: {
    position: "absolute",
    bottom: 2,
    right: 2,
    backgroundColor: "rgba(0,0,0,0.6)",
    borderRadius: 8,
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  promptScrollWheelEmojiBadgeText: {
    fontSize: 14,
  },
});
